//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetFood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetFood()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.Carts = new HashSet<Cart>();
        }
    
        public string pf_id { get; set; }
        public string pf_name { get; set; }
        public string pf_image { get; set; }
        public Nullable<int> pf_prices { get; set; }
        public Nullable<int> pf_salePrice { get; set; }
        public Nullable<int> pf_amount { get; set; }
        public string pf_status { get; set; }
        public Nullable<int> t_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Type Type { get; set; }
    }
}
