//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetMedicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetMedicine()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.Carts = new HashSet<Cart>();
        }
    
        public string pm_id { get; set; }
        public string pm_name { get; set; }
        public string pm_image { get; set; }
        public Nullable<int> pm_prices { get; set; }
        public Nullable<int> pm_salePrice { get; set; }
        public Nullable<int> pm_amount { get; set; }
        public string pm_description { get; set; }
        public string pm_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
