//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetToy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetToy()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.Carts = new HashSet<Cart>();
        }
    
        public string pt_id { get; set; }
        public string pt_name { get; set; }
        public string pt_image { get; set; }
        public Nullable<int> pt_prices { get; set; }
        public Nullable<int> pt_salePrice { get; set; }
        public Nullable<int> pt_amount { get; set; }
        public string pt_description { get; set; }
        public Nullable<System.DateTime> pt_published { get; set; }
        public string pt_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
